import { NextRequest } from 'next/server';
import { ok, fail } from '@/lib/api';
import { prisma } from '@/lib/prisma';
import { getCurrentContext } from '@/lib/session';

export const dynamic = 'force-dynamic';

function impactToPriority(impact: string): string {
  const i = impact.toLowerCase();
  if (i.startsWith('+') || i.includes('high') || i.includes('alt') || i.includes('critic')) return 'HIGH';
  if (i.includes('save') || i.includes('risparm') || i.includes('med')) return 'MEDIUM';
  return 'LOW';
}

function toneToType(tone: string): string {
  switch (tone.toLowerCase()) {
    case 'urgent':
    case 'negative':   return 'WARNING';
    case 'positive':   return 'OPPORTUNITY';
    case 'analytical': return 'STRATEGY';
    case 'action':     return 'ACTION';
    default:           return 'STRATEGY';
  }
}

const PRIORITY_RANK: Record<string, number> = { HIGH: 0, MEDIUM: 1, LOW: 2 };

export async function GET(req: NextRequest) {
  try {
    const { organizationId } = await getCurrentContext();

    const rows = await prisma.insight.findMany({
      where: { organizationId },
      orderBy: { createdAt: 'desc' },
    });

    const insights = rows
      .map((r) => {
        const row = r as typeof r & { type?: string | null; priority?: string | null; status?: string | null; content?: string | null };
        return {
          id: r.id,
          type: row.type ?? toneToType(r.tone ?? ''),
          priority: row.priority ?? impactToPriority(r.impact ?? ''),
          status: row.status ?? 'NEW',
          title: r.title,
          summary: r.summary,
          content: row.content ?? r.summary,
          confidence: 0.8,
          // True only for rows written by a real model call (Insight.source =
          // "ai:<model>"). Seed/demo rows have source NULL and must NOT carry the
          // "generated by AI" badge — that badge is an AI Act disclosure, not
          // decoration.
          aiGenerated: (r.source ?? '').startsWith('ai:'),
          createdAt: r.createdAt.toISOString(),
          updatedAt: r.createdAt.toISOString(),
        };
      })
      .sort(
        (a, b) =>
          (PRIORITY_RANK[a.priority] ?? 9) - (PRIORITY_RANK[b.priority] ?? 9) ||
          (a.createdAt < b.createdAt ? 1 : -1),
      );

    const sp = req.nextUrl.searchParams;
    const typeFilter = sp.get('type');
    const priorityFilter = sp.get('priority');
    const filtered = insights.filter(
      (i) =>
        (!typeFilter || i.type === typeFilter) &&
        (!priorityFilter || i.priority === priorityFilter),
    );

    return ok({ insights: filtered });
  } catch (e) {
    return fail((e as Error).message, 500);
  }
}
