export type ChatMessageDTO = {
  id: string;
  role: string;
  content: string;
  createdAt: string;
};

export type ConversationListItemDTO = {
  id: string;
  title: string;
  updatedAt: string;
  messageCount: number;
};

export type ConversationDetailDTO = {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  messages: ChatMessageDTO[];
};

export type SendMessageResponse = {
  conversation: ConversationDetailDTO;
  creditsRemaining: number;
};

export type InsightDTO = {
  id: string;
  type: string;
  priority: string;
  status: string;
  title: string;
  summary: string;
  content: string;
  confidence: number;
  /**
   * True only when the row was written by a real Anthropic call. Drives the
   * "generated by AI" badge, which is an AI Act disclosure and must never appear
   * on seed/demo rows. Optional so older cached responses degrade to "no badge",
   * which is the safe direction.
   */
  aiGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
};

export type GenerateInsightsResponse = {
  insights: InsightDTO[];
  creditsRemaining: number;
};

export type AlertSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type AlertStatus = 'NEW' | 'READ' | 'RESOLVED' | 'DISMISSED';

export type AlertAnalysisDTO = {
  explanation: string;
  actions: string[];
};

export type AlertDTO = {
  id: string;
  severity: AlertSeverity;
  status: AlertStatus;
  title: string;
  description: string;
  source: string;
  recommendation: string;
  aiAnalysis: AlertAnalysisDTO | null;
  createdAt: string;
  updatedAt: string;
};

export type AnalyzeAlertResponse = AlertAnalysisDTO & {
  cached: boolean;
  creditsRemaining?: number;
};
