import { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { ok, fail } from '@/lib/api';
import { prisma } from '@/lib/prisma';
import { getAuthContext } from '@/lib/session';
import { checkRateLimit, getClientIp, retryAfterSeconds } from '@/lib/rate-limit';
import { requireActiveAccess } from '@/lib/billing/server-gate';
import { consumeCredits, refundCredits, InsufficientCreditsError } from '@/lib/credits';
import { isAnthropicConfigured, MISSING_KEY_MESSAGE } from '@/lib/ai/client';
import { loadBusinessContext } from '@/lib/ai-context';
import {
  generateInsights,
  InvalidInsightResponseError,
  AI_SOURCE,
} from '@/lib/ai/insights-generation';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Generates real AI insights from the organization's real data, ON DEMAND only
 * (founder's decision: a button, never a background job).
 *
 * This route replaces a permanent stub that always answered 503
 * "AI_DISABLED_IN_DEMO" while the page showed seed rows badged "generated by AI".
 *
 * Order of the guards is deliberate — every cheap refusal happens before the
 * expensive one, so a request that can never reach Anthropic is never billed:
 *   401 auth → 402 trial gate → 429 rate limit → 400 input → 503 no API key
 *   → 422 not enough data → credits → model call → validation → write.
 */

// Cost per generation. 3 credits, the value the UI has always advertised
// ("Genera Nuovi Insight (3 crediti)" in it.json/en.json) and the threshold the
// old stub already enforced. Deliberately more than the 1 credit of a chat turn
// or an alert analysis: this call produces 3-5 pieces of written advice.
const GENERATION_CREDIT_COST = 3;

const GenerateSchema = z.object({
  // The locale the user is actually looking at. Optional: falls back to the
  // user's stored preference, then Italian — same shape used by the register and
  // forgot-password routes.
  locale: z.enum(['it', 'en']).optional(),
});

function tooManyRequests(reset: number) {
  return NextResponse.json(
    { success: false, error: 'RATE_LIMITED' },
    { status: 429, headers: { 'Retry-After': String(retryAfterSeconds(reset)) } },
  );
}

export async function POST(req: NextRequest) {
  try {
    // 1. Auth (strict): a real logged-in user with an org, no demo fallback.
    const authCtx = await getAuthContext();
    if (!authCtx) return fail('Unauthorized', 401);
    const { userId, organizationId } = authCtx;

    // 2. Trial/subscription gate, as on every other credit-consuming AI route.
    const access = await requireActiveAccess(organizationId);
    if (!access.allowed) return fail('TRIAL_EXPIRED', 402);

    // 3. Rate limit per IP+org. Shares the 'ai-analyze' budget: it is the same
    //    resource being protected (expensive Anthropic calls from one org).
    const rl = await checkRateLimit('ai-analyze', `${getClientIp(req)}:org:${organizationId}`);
    if (!rl.success) return tooManyRequests(rl.reset);

    // 4. Input. An absent body is fine — locale is optional.
    const json = await req.json().catch(() => null);
    const parsed = GenerateSchema.safeParse(json ?? {});
    if (!parsed.success) return fail('INVALID_INPUT', 400);

    // 5. Configuration guard.
    if (!isAnthropicConfigured()) return fail(MISSING_KEY_MESSAGE, 503);

    // 6. Real data. The facts engine is the materia prima: no facts and no
    //    monthly figures means there is nothing truthful to advise on, so we
    //    refuse BEFORE charging anything rather than pay for generic filler.
    const businessCtx = await loadBusinessContext(organizationId);
    const hasData = businessCtx.facts.length > 0 || businessCtx.financials.length > 0;
    if (!hasData) return fail('NOT_ENOUGH_DATA', 422);

    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { locale: true },
    });
    const locale = parsed.data.locale ?? (user?.locale === 'en' ? 'en' : 'it');

    // 7. Credits: charged HERE, the last gate before the Anthropic call, with the
    //    same atomic conditional UPDATE used by /api/ai/chat and /api/ai/analyze
    //    (…WHERE aiCredits >= cost), so concurrent requests can never drive the
    //    balance negative.
    let creditsRemaining: number;
    try {
      creditsRemaining = await consumeCredits(organizationId, GENERATION_CREDIT_COST);
    } catch (err) {
      if (err instanceof InsufficientCreditsError) return fail('INSUFFICIENT_CREDITS', 402);
      throw err;
    }

    // 8. Model call + validation. A malformed answer writes NOTHING.
    //
    //    Two distinct failure modes, two distinct policies:
    //      • InvalidInsightResponseError (the model answered, but not in a
    //        shape we can use — unparseable JSON, wrong enum values, or fewer
    //        than MIN_INSIGHTS survived validation): the credit IS refunded
    //        below. This is a format failure, not a "the user got advice and
    //        should pay for it" situation — the org would otherwise pay 3
    //        credits for literally nothing.
    //      • any other error (network failure, Anthropic outage, HTTP error):
    //        NOT refunded, matching chat and analyze — the Anthropic call was
    //        made and billed to us either way, and this is the same "model
    //        failure mid-stream" case those routes already accept as
    //        non-refundable.
    let generated;
    try {
      generated = await generateInsights(businessCtx, locale);
    } catch (err) {
      if (err instanceof InvalidInsightResponseError) {
        console.error('[ai/insights/generate] invalid model response:', err.reason);
        // Best-effort: if the refund itself fails, the generation error is
        // still what we report — the credit desync is logged for a manual fix
        // rather than masked behind a different error message.
        try {
          await refundCredits(organizationId, GENERATION_CREDIT_COST);
        } catch (refundErr) {
          console.error('[ai/insights/generate] credit refund FAILED after invalid response:', refundErr);
        }
        return fail('INVALID_AI_RESPONSE', 502);
      }
      console.error('[ai/insights/generate] Anthropic API error:', err);
      const msg = err instanceof Error ? err.message : 'AI request failed';
      return fail(msg, 502);
    }

    // 9. Persist. Added to the existing ones, never replacing them: an insight
    //    the user has already marked REVIEWED/IMPLEMENTED is their record of a
    //    decision and must not be deleted by a new generation.
    //    `source` marks these as genuinely AI-written — the UI badge reads it.
    await prisma.insight.createMany({
      data: generated.map((g) => ({
        organizationId,
        type: g.type,
        priority: g.priority,
        status: 'NEW',
        title: g.title,
        summary: g.summary,
        content: g.content,
        confidence: g.confidence,
        source: AI_SOURCE,
      })),
    });

    return ok({ created: generated.length, creditsRemaining });
  } catch (e) {
    console.error('[ai/insights/generate] unexpected error:', e);
    return fail((e as Error).message, 500);
  }
}
