/**
 * How the demo chat works — shared by the route and the chat page, so it holds
 * no server-only import.
 *
 * Founder's decision: the demo must cost nothing per visitor. A visitor picks
 * one of the questions below; each answer is generated by the AI once and then
 * served to everyone from the cache (@/lib/demo/answer-cache), until the demo
 * data, the model or the prompt change.
 */

/**
 * Free questions typed by the visitor (the route's `demoChat`, with its limits
 * per session, IP, day and month). Kept, switched off: every free question is
 * a call to the model paid by the founder.
 */
export const DEMO_FREE_QUESTIONS = false;

/**
 * The questions offered in the demo, chosen for what the demo data can answer
 * (monthly figures, category changes, receivables, recurring expenses, the
 * facts engine). The text of each is chat.demoQuestions.<id> in it.json/en.json.
 */
export const DEMO_SUGGESTED_QUESTIONS = [
  'costs',
  'revenue',
  'margin',
  'cashflow',
  'receivables',
  'expenses',
  'signals',
  'outlook',
] as const;

export type DemoSuggestedQuestion = (typeof DEMO_SUGGESTED_QUESTIONS)[number];
